export const dummyArrayOfDevelopers = [
  {
    id: 1,
    name: "John Doe",
    designation: "Data Scientist",
    description: "Passionate about analyzing data and extracting valuable insights.",
    experience: "5 years",
    image: "https://example.com/john-doe-image.jpg",
    rating: 4.7,
  },
  {
    id: 2,
    name: "Jane Smith",
    designation: "Fullstack Developer",
    description: "Experienced in building web applications from front to back.",
    experience: "7 years",
    image: "https://example.com/jane-smith-image.jpg",
    rating: 4.9,
  },
  {
    id: 3,
    name: "Mike Johnson",
    designation: "Front End Developer",
    description: "Enthusiastic about crafting beautiful and user-friendly interfaces.",
    experience: "3 years",
    image: "https://example.com/mike-johnson-image.jpg",
    rating: 4.5,
  },
  {
    id: 4,
    name: "Sarah Lee",
    designation: "Cloud Scientist",
    description: "Adept at deploying and managing applications in cloud environments.",
    experience: "6 years",
    image: "https://example.com/sarah-lee-image.jpg",
    rating: 4.2,
  },
  {
    id: 5,
    name: "Alex Brown",
    designation: "Backend Developer",
    description: "Proficient in building scalable and efficient server-side applications.",
    experience: "4 years",
    image: "https://example.com/alex-brown-image.jpg",
    rating: 4.8,
  },
  {
    id: 6,
    name: "Emily Wilson",
    designation: "Machine Learning Engineer",
    description: "Passionate about creating intelligent systems through machine learning.",
    experience: "8 years",
    image: "https://example.com/emily-wilson-image.jpg",
    rating: 4.3,
  },
  {
    id: 7,
    name: "Chris Turner",
    designation: "Mobile App Developer",
    description: "Skilled in developing native and cross-platform mobile applications.",
    experience: "5 years",
    image: "https://example.com/chris-turner-image.jpg",
    rating: 4.6,
  },
  {
    id: 8,
    name: "Laura Adams",
    designation: "DevOps Engineer",
    description: "Expert in automating and streamlining development and deployment processes.",
    experience: "9 years",
    image: "https://example.com/laura-adams-image.jpg",
    rating: 4.0,
  },
  {
    id: 9,
    name: "Tom Walker",
    designation: "UI/UX Designer",
    description: "Passionate about creating visually appealing and intuitive user experiences.",
    experience: "6 years",
    image: "https://example.com/tom-walker-image.jpg",
    rating: 4.6,
  },
  {
    id: 10,
    name: "Sophia Kim",
    designation: "Software Engineer",
    description: "Experienced in designing and building software applications.",
    experience: "7 years",
    image: "https://example.com/sophia-kim-image.jpg",
    rating: 4.4,
  },
  {
    id: 11,
    name: "Robert Clark",
    designation: "Game Developer",
    description: "Enthusiastic about creating immersive and entertaining gaming experiences.",
    experience: "4 years",
    image: "https://example.com/robert-clark-image.jpg",
    rating: 4.5,
  },
  {
    id: 12,
    name: "Ava Martinez",
    designation: "Security Analyst",
    description: "Specialized in identifying and mitigating security risks.",
    experience: "5 years",
    image: "https://example.com/ava-martinez-image.jpg",
    rating: 4.7,
  },
  {
    id: 13,
    name: "Daniel Cooper",
    designation: "Embedded Systems Engineer",
    description: "Skilled in designing and developing embedded systems for various applications.",
    experience: "6 years",
    image: "https://example.com/daniel-cooper-image.jpg",
    rating: 4.2,
  },
  {
    id: 14,
    name: "Olivia Hughes",
    designation: "Blockchain Developer",
    description: "Passionate about creating decentralized and secure applications.",
    experience: "3 years",
    image: "https://example.com/olivia-hughes-image.jpg",
    rating: 4.6,
  },
  {
    id: 15,
    name: "William Turner",
    designation: "Data Engineer",
    description: "Expert in designing and managing data pipelines and warehouses.",
    experience: "8 years",
    image: "https://example.com/william-turner-image.jpg",
    rating: 4.3,
  },
  {
    id: 16,
    name: "Ella Collins",
    designation: "QA Automation Engineer",
    description: "Adept at automating testing processes to ensure software quality.",
    experience: "4 years",
    image: "https://example.com/ella-collins-image.jpg",
    rating: 4.8,
  },
  {
    id: 17,
    name: "James Ward",
    designation: "AR/VR Developer",
    description: "Experienced in creating augmented and virtual reality applications.",
    experience: "5 years",
    image: "https://example.com/james-ward-image.jpg",
    rating: 4.4,
  },
  {
    id: 18,
    name: "Grace Allen",
    designation: "Frontend Architect",
    description: "Skilled in designing scalable and maintainable frontend architectures.",
    experience: "6 years",
    image: "https://example.com/grace-allen-image.jpg",
    rating: 4.7,
  },
  {
    id: 19,
    name: "Michael Lee",
    designation: "Big Data Analyst",
    description: "Passionate about analyzing and visualizing large datasets.",
    experience: "4 years",
    image: "https://example.com/michael-lee-image.jpg",
    rating: 4.1,
  },
  {
    id: 20,
    name: "Isabella Rodriguez",
    designation: "Robotics Engineer",
    description: "Specialized in designing and developing robotic systems.",
    experience: "3 years",
    image: "https://example.com/isabella-rodriguez-image.jpg",
    rating: 4.5,
  },
];
